package net.journey.dimension.senterian;

import net.journey.JourneyBlocks;
import net.journey.util.Config;
import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.util.BlockPos;
import net.minecraft.util.MathHelper;
import net.minecraft.world.Teleporter;
import net.minecraft.world.World;
import net.minecraft.world.WorldServer;

public class TeleporterSenterian extends Teleporter {
	
	protected WorldServer world;

	public TeleporterSenterian(WorldServer world) {
		super(world);
		this.world = world;
	}

	@Override
	public boolean placeInExistingPortal(Entity entityIn, float rotationYaw) {
        SenterianPortalCoords coords = SenterianPortalCoords.getPortalProperties((EntityPlayer)entityIn);
	    if (entityIn.dimension == Config.senterian) {        
            int chunkX = (MathHelper.floor_double(entityIn.posX) & ~0xf);
            int chunkZ = (MathHelper.floor_double(entityIn.posZ) & ~0xf);
            int y;

            coords.setReturnPortalX(entityIn.posX);
            coords.setReturnPortalY(entityIn.posY);
            coords.setReturnPortalZ(entityIn.posZ);

            for (y = 9; y < 40; y += 8) {
                if (this.world.getBlockState(new BlockPos(chunkX + 7, y, chunkZ + 7)) == JourneyBlocks.senterianPortal) {
                    entityIn.setLocationAndAngles(chunkX + 7.5D, y + 0.5D, chunkZ + 7.5D, entityIn.rotationYaw, 0.0F);
                    entityIn.motionX = entityIn.motionY = entityIn.motionZ = 0.0D;            
                    return true;
                }
            }
            
            for (y = 8; y < 40; y += 8) {
                if (this.world.getBlockState(new BlockPos(chunkX + 7, y, chunkZ + 7)) !=Blocks.air.getDefaultState() && 
                	this.world.getBlockState(new BlockPos(chunkX + 7, y + 8, chunkZ + 7)) !=Blocks.air.getDefaultState()) {
                	
                    generatePortalRoom(this.world, chunkX, y, chunkZ);
                    entityIn.setLocationAndAngles(chunkX + 7.5D, y + 1.5D, chunkZ + 7.5D, entityIn.rotationYaw, 0.0F);
                    entityIn.motionX = entityIn.motionY = entityIn.motionZ = 0.0D;
                    return true;
                }
            }
	    } else {
            entityIn.setLocationAndAngles(
            		coords.getReturnPortalX(), 
            		coords.getReturnPortalY(), 
            		coords.getReturnPortalZ(), 
            entityIn.rotationYaw, 0.0F);
            		entityIn.motionX = 
            		entityIn.motionY =
            		entityIn.motionZ = 0.0D;            
            return true;
	    }
	    
	    return false;
	}

	public void generatePortalRoom(World world, int i, int j, int k) {

        for(int 
        		n = 0; 
        		n < 16; 
        		n++) {
            for(int 
            		m = 0; 
            		m < 16; 
            		m++) {
                for(int 
                		o = 1; 
                		o < 8; 
                		o++) {
                    world.setBlockState(new BlockPos(i+n, j+o, k+m), Blocks.air.getDefaultState());
                }
            }
        }
        world.setBlockState(new BlockPos(i + 0, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 1), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 2), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 3), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 4), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 10), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 11), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 12), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 13), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 1), JourneyBlocks.senterianGuardianLamp.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 13), JourneyBlocks.senterianGuardianLamp.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 6), JourneyBlocks.senterianPortalFrame.getStateFromMeta(7));
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 7), JourneyBlocks.senterianPortalFrame.getStateFromMeta(7));
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 8), JourneyBlocks.senterianPortalFrame.getStateFromMeta(7));
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 1), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 2), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 3), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 4), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 10), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 11), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 12), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 13), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 5), JourneyBlocks.senterianPortalFrame.getStateFromMeta(4));
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 6), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 7), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 8), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 9), JourneyBlocks.senterianPortalFrame.getStateFromMeta(6));
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 5), JourneyBlocks.senterianPortalFrame.getStateFromMeta(4));
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 6), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 7), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 8), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 9), JourneyBlocks.senterianPortalFrame.getStateFromMeta(6));
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 5), JourneyBlocks.senterianPortalFrame.getStateFromMeta(4));
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 6), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 7), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 8), JourneyBlocks.senterianPortal.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 9), JourneyBlocks.senterianPortalFrame.getStateFromMeta(6));
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 6), JourneyBlocks.senterianPortalFrame.getStateFromMeta(5));
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 7), JourneyBlocks.senterianPortalFrame.getStateFromMeta(5));
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 8), JourneyBlocks.senterianPortalFrame.getStateFromMeta(5));
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 1), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 2), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 3), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 4), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 10), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 11), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 12), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 13), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 11, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 12, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 1), JourneyBlocks.senterianGuardianLamp.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 13), JourneyBlocks.senterianGuardianLamp.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 1, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 1, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 1, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 1, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 2, k + 0), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 2, k + 5), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 2, k + 9), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 2, k + 14), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 3, k + 0), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 3, k + 5), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 3, k + 9), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 3, k + 14), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 13, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 0, k + 14), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 1, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 1), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 2), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 3), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 4), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 10), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 11), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 12), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 13), JourneyBlocks.senterianBars.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 2, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 0), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 1), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 2), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 3), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 4), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 5), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 9), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 10), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 11), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 12), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 13), JourneyBlocks.senterianBricks.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 3, k + 14), JourneyBlocks.senterianCarvedRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 0), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 1), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 2), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 3), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 4), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 5), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 6), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 7), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 8), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 9), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 10), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 11), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 12), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 13), JourneyBlocks.senterianRock.getDefaultState());
		world.setBlockState(new BlockPos(i + 14, j + 4, k + 14), JourneyBlocks.senterianRock.getDefaultState());
	}
	
	@Override
	public boolean makePortal(Entity entity) {
	    return false;
	}
}